trigger:
- main
 
variables:
  RUN_SETUP: "false"
 
stages:
 
# =========================================
# SETUP WORKSPACES
# =========================================
- stage: Setup
  displayName: "Inicializar Workspaces"
  condition: eq(variables['RUN_SETUP'], 'true')
  jobs:
  - job: InitWorkspaces
    displayName: "Crear Workspaces Terraform"
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-terraform-conn'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install terraform -y
          terraform -version
          cd terraform
          terraform init
          terraform workspace select dev || terraform workspace new dev
          terraform workspace select staging || terraform workspace new staging
          terraform workspace select prod || terraform workspace new prod
          terraform workspace list
 
# =========================================
# VALIDATE TERRAFORM
# =========================================
- stage: Validate
  displayName: "Validar Terraform"
  dependsOn: []
  jobs:
  - job: ValidateTerraform
    displayName: "Terraform Validate"
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-terraform-conn'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install terraform -y
          terraform -version
          cd terraform
          terraform init
          terraform fmt -check
          terraform validate
 
# =========================================
# DEPLOY DEV
# =========================================
- stage: Deploy_DEV
  displayName: "Deploy DEV"
  dependsOn: Validate
  jobs:
  - deployment: DeployDev
    displayName: "Despliegue DEV"
    environment: dev
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-terraform-conn'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Instalando Terraform..."
                curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                sudo apt-get update
                sudo apt-get install terraform -y
                terraform -version
                cd terraform
                terraform init
                terraform workspace select dev || terraform workspace new dev
                terraform apply -auto-approve
 
# =========================================
# DEPLOY STAGING
# =========================================
- stage: Deploy_STAGING
  displayName: "Deploy STAGING"
  dependsOn: Deploy_DEV
  jobs:
  - deployment: DeployStaging
    displayName: "Desplegar STAGING"
    environment: staging
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-terraform-conn'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                sudo apt-get update
                sudo apt-get install terraform -y
                terraform -version
                cd terraform
                terraform init
                terraform workspace select staging || terraform workspace new staging
                terraform apply -auto-approve
 
# =========================================
# DEPLOY PROD
# =========================================
- stage: Deploy_PROD
  displayName: "Deploy PROD"
  dependsOn: Deploy_STAGING
  jobs:
  - deployment: DeployProd
    displayName: "Desplegar PROD"
    environment: prod
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-terraform-conn'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                sudo apt-get update
                sudo apt-get install terraform -y
                terraform -version
                cd terraform
                terraform init
                terraform workspace select prod || terraform workspace new prod
                terraform apply -auto-approve