trigger:
- main

variables:
  RUN_SETUP: "false"

stages:

# INIT
- stage: Setup
  displayName: "Inicializar Workspaces"
  condition: eq(variables['RUN_SETUP'], 'true')
  jobs:
  - job: init
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: bash scripts/init-workspaces.sh
      displayName: "Inicializar Workspaces de Terraform"

# VALIDACIÓN
- stage: Validate
  jobs:
  - job: validate
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        cd terraform
        terraform init
        terraform validate
      displayName: "Validar Terraform"

# DEV
- stage: Deploy_DEV
  jobs:
  - job: deploy
    steps:
    - script: |
        cd terraform
        terraform workspace select dev
        terraform apply -auto-approve

# STAGING
- stage: Deploy_STAGING
  dependsOn: Deploy_DEV
  jobs:
  - job: deploy
    steps:
    - script: |
        cd terraform
        terraform workspace select staging
        terraform apply -auto-approve

# PROD
- stage: Deploy_PROD
  dependsOn: Deploy_STAGING
  jobs:
  - job: deploy
    steps:
    - script: |
        cd terraform
        terraform workspace select prod
        terraform apply -auto-approve